name: Build and run everything
on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * 1'
jobs:
  build-all-alpine:
    runs-on: ubuntu-latest
    container:
      image: alpine:latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Install bash
        run: apk add bash git
      - name: Silence some git warnings
        run: |
          git config --global advice.detachedHead false
          git config --global init.defaultBranch main
      - name: Install and build all benchmarks and allocators
        # dh: glibc-specific
        # fg: Uses execinfo.h, which is a GNU extension
        # gd: ?
        # hd: glibc-specific
        # lf: crashes redis server
        # lt: return type 'struct mallinfo' is incomplete
        # mesh/nomesh: infinite loop?
        # pa: can't setup depot_tools and goma
        # sm: ../src/supermalloc.h:10:31: error: expected initializer before '__THROW'
        # tcg: [...] specifies less restrictive attribute than its target [...]
        # lp: /__w/mimalloc-bench/mimalloc-bench/extern/lp/Source/bmalloc/libpas/src/libpas/pas_thread_local_cache.c:218:22: error: call to undeclared function 'pthread_getname_np'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
        run: ./build-bench-env.sh all no-dh no-hd no-sm no-mesh no-nomesh no-pa no-gd no-fg no-lf no-lt no-tcg no-lp
      - name: Run everything.
        run: |
          cd out/bench
          ../../bench.sh alla allt
  build-all-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Silence some git warnings
        run: |
          git config --global advice.detachedHead false
          git config --global init.defaultBranch main
      - name: Install and build all benchmarks and allocators
        # fg: crashes on redis
        # gd: infinite loop in the redis benchmark
        # lt: breaks on sh8benchN
        # lf: crashes redis server
        # ff: crashes on modern ubuntu: https://github.com/bwickman97/ffmalloc/issues/5
        # hoard: crashes on rocksdb
        # tcg: https://github.com/google/tcmalloc/issues/155
        # pa: python3: can't open file '/__w/mimalloc-bench/mimalloc-bench/extern/pa/partition_alloc_builder/tools/rust/update_rust.py': [Errno 2] No such file or directory
        run: ./build-bench-env.sh all no-lean no-gd no-ff no-fg no-lt no-lf no-hd no-tcg no-pa
      - name: Run everything.
        run: |
          cd out/bench
          ../../bench.sh alla allt
  build-all-fedora:
    runs-on: ubuntu-latest
    container:
      image: fedora:latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Install git
        run: sudo dnf -y --quiet --nodocs install git
      - name: Silence some git warnings
        run: |
          git config --global advice.detachedHead false
          git config --global init.defaultBranch main
      - name: Install and build all benchmarks and allocators
        # gd: infinite loop in the redis benchmark
        # mesh/nomesh: error: '__malloc_hook' was not declared in this scope;
        # mi: error: '__malloc_hook' was not declared in this scope;
        # rp: mixing declarations and code is incompatible with standards before C99
        # lf: crashes redis server
        # fg: crashes redis server
        # pa: python3: can't open file '/__w/mimalloc-bench/mimalloc-bench/extern/pa/partition_alloc_builder/tools/rust/update_rust.py': [Errno 2] No such file or directory
        # lp: /__w/mimalloc-bench/mimalloc-bench/extern/lp/Source/bmalloc/libpas/src/libpas/pas_thread_local_cache.c:218:22: error: call to undeclared function 'pthread_getname_np'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
        # tcg: https://github.com/google/tcmalloc/issues/179
        run: ./build-bench-env.sh all no-lean no-mi no-mesh no-nomesh no-gd no-rp no-lf no-fg no-pa no-lp no-tcg
      - name: Run everything.
        run: |
          cd out/bench
          ../../bench.sh alla allt
  build-all-osx:
    runs-on: macos-11
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Silence some git warnings
        run: |
          git config --global advice.detachedHead false
          git config --global init.defaultBranch main
      - name: Install and build all benchmarks and allocators
        # ff:ffmalloc.c:1140:14: error: implicit declaration of function 'sched_getcpu' is invalid in C99 [-Werror,-Wimplicit-function-declaration] 
        # fg: unknown type name 'pthread_spinlock_t'; did you mean 'pthread_rwlock_t'?
        # gd: so many errors
        # pa: ninja: error: '../../buildtools/third_party/libc++/trunk/src/utility.cpp', needed by 'obj/buildtools/third_party/libc++/libc++/utility.o', missing and no known rule to make it
        run: ./build-bench-env.sh all no-lean no-gd no-ff no-fg no-pa
      - name: Run everything.
        run: |
          cd out/bench
          ../../bench.sh alla allt
